DROP DATABASE IF EXISTS worms;
CREATE DATABASE worms;
USE worms;

CREATE TABLE user (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nickname VARCHAR(30) NOT NULL,
    password VARCHAR(30),
    gamesplayed INT
)ENGINE=InnoDB;

CREATE TABLE chat (
    id INT PRIMARY KEY AUTO_INCREMENT,
    message VARCHAR(100),
    sender VARCHAR(30),
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB;

CREATE TABLE results (
    id INT PRIMARY KEY AUTO_INCREMENT,
    maxpoints INT,
    user INT,
	time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user) REFERENCES user(id)
)ENGINE=InnoDB;